In [202]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [203]:
df = pd.read_csv('data/messy_linear_regression_data.csv')
df.head()

,Age,Experience_Years,Salary,City,Education_Level,Performance_Score,Working_Hours_Per_Week,Random_Noise_Text
0,20.0,21.0,81086.0,Chennai,Bachelors,7.504843403460779,44.0,NaN
1,35.0,30.0,35674.0,Delhi,PhD,7.291322654303698,50.0,rsFUOEbM
2,43.0,15.0,56105.0,Bhubaneswar,PhD,2.715327982680152,69.0,NaN
3,28.0,14.0,111618.0,Mumbai,Bachelors,8.521594893906492,62.0,NaN
4,23.0,27.0,132053.0,Chennai,NaN,unknown,26.0,peVYSkBj

In [204]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13536 entries, 0 to 13535
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     12877 non-null  str
 1   Experience_Years        12858 non-null  float64
 2   Salary                  12866 non-null  float64
 3   City                    12875 non-null  str
 4   Education_Level         12886 non-null  str
 5   Performance_Score       12878 non-null  str
 6   Working_Hours_Per_Week  12857 non-null  float64
 7   Random_Noise_Text       4112 non-null   str
dtypes: float64(3), str(5)
memory usage: 846.1 KB

In [205]:
df = df.drop(columns=["Random_Noise_Text"])
df = df.dropna(subset=["Salary"])

In [206]:
df.isnull().sum()

Age                       621
Experience_Years          649
Salary                      0
City                      633
Education_Level           621
Performance_Score         622
Working_Hours_Per_Week    646
dtype: int64

In [207]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [208]:
df["Performance_Score"] = pd.to_numeric(df["Performance_Score"], errors="coerce")

In [209]:
df["Performance_Score"]=df["Performance_Score"].fillna(df["Performance_Score"].median())
df['Working_Hours_Per_Week']=df['Working_Hours_Per_Week'].fillna(df["Working_Hours_Per_Week"].median())
df["Education_Level"]=df["Education_Level"].fillna(df["Education_Level"].mode()[0])
df['City']=df['City'].fillna(df["City"].mode()[0])
df = df[df["Experience_Years"] <= df["Age"]]

In [210]:
df.head()

,Age,Experience_Years,Salary,City,Education_Level,Performance_Score,Working_Hours_Per_Week
1,35.0,30.0,35674.0,Delhi,PhD,7.291323,50.0
2,43.0,15.0,56105.0,Bhubaneswar,PhD,2.715328,69.0
3,28.0,14.0,111618.0,Mumbai,Bachelors,8.521595,62.0
6,42.0,24.0,76714.0,Bhubaneswar,masters,2.086179,27.0
7,42.0,31.0,144083.0,Mumbai,PhD,4.632194,28.0

In [211]:
df["Education_Level"] = df["Education_Level"].str.strip().str.lower()
df["City"] = df["City"].str.strip().str.lower()
df = pd.get_dummies(df, columns=["City", "Education_Level"],dtype=int, drop_first=True)

In [212]:
df.isnull().sum()
# df.dtypes

Age                        0
Experience_Years           0
Salary                     0
Performance_Score          0
Working_Hours_Per_Week     0
City_chennai               0
City_delhi                 0
City_kolkata               0
City_mumbai                0
Education_Level_diploma    0
Education_Level_masters    0
Education_Level_phd        0
dtype: int64

In [213]:
df.head()

,Age,Experience_Years,Salary,Performance_Score,Working_Hours_Per_Week,City_chennai,City_delhi,City_kolkata,City_mumbai,Education_Level_diploma,Education_Level_masters,Education_Level_phd
1,35.0,30.0,35674.0,7.291323,50.0,0,1,0,0,0,0,1
2,43.0,15.0,56105.0,2.715328,69.0,0,0,0,0,0,0,1
3,28.0,14.0,111618.0,8.521595,62.0,0,0,0,1,0,0,0
6,42.0,24.0,76714.0,2.086179,27.0,0,0,0,0,0,1,0
7,42.0,31.0,144083.0,4.632194,28.0,0,0,0,1,0,0,1

In [227]:
print(df.corr()["Salary"].sort_values(ascending=False))

Salary                     1.000000
City_chennai               0.016975
Education_Level_masters    0.012419
Experience_Years           0.009210
City_kolkata               0.008508
Performance_Score          0.001061
Age                        0.000721
City_mumbai               -0.005267
Working_Hours_Per_Week    -0.007814
City_delhi                -0.008186
Education_Level_phd       -0.009772
Education_Level_diploma   -0.018118
Name: Salary, dtype: float64

In [214]:
x = df.drop(columns=["Salary"])
y = df["Salary"]

In [215]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3, random_state=42)

In [216]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# xtrain= scaler.fit_transform(xtrain)
# xtest = scaler.transform(xtest)

In [217]:
LinearRegModel = LinearRegression()
LinearRegModel.fit(xtrain, ytrain)

LinearRegression()

In [218]:
ypred = LinearRegModel.predict(xtest)

In [219]:
print('training score:', LinearRegModel.score(xtrain, ytrain))
print('testing score:', LinearRegModel.score(xtest, ytest))

training score: 0.001066995503225865
testing score: 0.0009521945768687923

### xgboost regressor

In [220]:
from xgboost import XGBRegressor
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [3, 5, 7],
    "learning_rate": [0.01, 0.1],
}
model=XGBRegressor(objective="reg:squarederror",
    random_state=42)
grid=GridSearchCV(estimator=model,param_grid=param_grid, cv=5)
grid.fit(xtrain,ytrain)

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, max_bin=None,
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             param_grid={'learning_rate': [0.01, 0.1], 'max_depth': [3, 5, 7],
                         'n_estimators': [100, 200]})

In [221]:
print('best parameter: ',grid.best_params_)
print('Best score', grid.best_score_)

best parameter:  {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100}
Best score -0.004275554219947297

In [222]:

xtgbrmodel=XGBRegressor(n_estimators=100, learning_rate=0.01, max_depth=3, random_state=42)
xtgbrmodel.fit(xtrain, ytrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [223]:
ypred=xtgbrmodel.predict(xtest)

In [224]:
print('training score:', xtgbrmodel.score(xtrain, ytrain))
print('testing score:', xtgbrmodel.score(xtest, ytest))

training score: 0.028354992723652495
testing score: -0.002852944995098028

# Random forest regressor

In [225]:
from sklearn.ensemble import RandomForestRegressor
rfmodel = RandomForestRegressor(n_estimators=300, random_state=42)
rfmodel.fit(xtrain, ytrain)
ypred_rf = rfmodel.predict(xtest)

In [226]:
print('training score:', rfmodel.score(xtrain, ytrain))
print('testing score:', rfmodel.score(xtest, ytest))

training score: 0.8460574271106054
testing score: -0.04885394139537835

In [228]:
from sklearn.dummy import DummyRegressor

dummy = DummyRegressor(strategy="mean")
dummy.fit(xtrain, ytrain)

print("Dummy Train Score:", dummy.score(xtrain, ytrain))
print("Dummy Test Score:", dummy.score(xtest, ytest))

Dummy Train Score: 0.0
Dummy Test Score: -0.00029156109991501644

In [229]:
dff = pd.read_csv('data/messy_linear_regression_data.csv')
dff.head()

,Age,Experience_Years,Salary,City,Education_Level,Performance_Score,Working_Hours_Per_Week,Random_Noise_Text
0,20.0,21.0,81086.0,Chennai,Bachelors,7.504843403460779,44.0,NaN
1,35.0,30.0,35674.0,Delhi,PhD,7.291322654303698,50.0,rsFUOEbM
2,43.0,15.0,56105.0,Bhubaneswar,PhD,2.715327982680152,69.0,NaN
3,28.0,14.0,111618.0,Mumbai,Bachelors,8.521594893906492,62.0,NaN
4,23.0,27.0,132053.0,Chennai,NaN,unknown,26.0,peVYSkBj

In [230]:
dff.dropna(inplace=True)

In [231]:
dff.info()

<class 'pandas.DataFrame'>
Index: 2924 entries, 1 to 13532
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     2924 non-null   str
 1   Experience_Years        2924 non-null   float64
 2   Salary                  2924 non-null   float64
 3   City                    2924 non-null   str
 4   Education_Level         2924 non-null   str
 5   Performance_Score       2924 non-null   str
 6   Working_Hours_Per_Week  2924 non-null   float64
 7   Random_Noise_Text       2924 non-null   str
dtypes: float64(3), str(5)
memory usage: 205.6 KB

In [232]:
dff = dff.drop(columns=["Random_Noise_Text"])
dff["Performance_Score"] = pd.to_numeric(dff["Performance_Score"], errors="coerce")
dff["Age"] = pd.to_numeric(dff["Age"], errors="coerce")
dff = dff.dropna()
dff.isna().sum()

Age                       0
Experience_Years          0
Salary                    0
City                      0
Education_Level           0
Performance_Score         0
Working_Hours_Per_Week    0
dtype: int64

In [233]:
dff.info()

<class 'pandas.DataFrame'>
Index: 2799 entries, 1 to 13532
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     2799 non-null   float64
 1   Experience_Years        2799 non-null   float64
 2   Salary                  2799 non-null   float64
 3   City                    2799 non-null   str
 4   Education_Level         2799 non-null   str
 5   Performance_Score       2799 non-null   float64
 6   Working_Hours_Per_Week  2799 non-null   float64
dtypes: float64(5), str(2)
memory usage: 174.9 KB

In [234]:
dff["Education_Level"] = dff["Education_Level"].str.strip().str.lower()
dff["City"] = dff["City"].str.strip().str.lower()
dff = pd.get_dummies(dff, columns=["City", "Education_Level"],dtype=int, drop_first=True)
dff.head()

,Age,Experience_Years,Salary,Performance_Score,Working_Hours_Per_Week,City_chennai,City_delhi,City_kolkata,City_mumbai,Education_Level_diploma,Education_Level_masters,Education_Level_phd
1,35.0,30.0,35674.0,7.291323,50.0,0,1,0,0,0,0,1
6,42.0,24.0,76714.0,2.086179,27.0,0,0,0,0,0,1,0
10,66.0,27.0,83711.0,6.171607,58.0,0,0,0,0,0,1,0
12,35.0,18.0,47916.0,6.956210,28.0,0,1,0,0,0,1,0
16,65.0,15.0,52916.0,5.363320,20.0,1,0,0,0,1,0,0

In [235]:
model = LinearRegression()
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3, random_state=42)
model.fit(xtrain, ytrain)

LinearRegression()

In [236]:
print('training score:', model.score(xtrain, ytrain))
print('testing score:', model.score(xtest, ytest))

training score: 0.001066995503225865
testing score: 0.0009521945768687923

In [237]:
from sklearn.ensemble import RandomForestRegressor
rfmodel = RandomForestRegressor(n_estimators=300, random_state=42)
rfmodel.fit(xtrain, ytrain)
ypred_rf = rfmodel.predict(xtest)

In [238]:
print('training score:', rfmodel.score(xtrain, ytrain))
print('testing score:', rfmodel.score(xtest, ytest))

training score: 0.8460574271106054
testing score: -0.04885394139537835