In [3]:
import pandas as pd

In [4]:
# label encodding 
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df=pd.DataFrame({'Gender':['M','F','M','M','F']})
df

  Gender
0      M
1      F
2      M
3      M
4      F

In [5]:
df['Gender']=le.fit_transform(df['Gender'])
df

   Gender
0       1
1       0
2       1
3       1
4       0

In [6]:
df2=pd.DataFrame({'city':['Newwork','London','Paris','Tokyo','Newdelhi']}
)

In [7]:
df2['city']=le.fit_transform(df2['city'])
df2

   city
0     2
1     0
2     3
3     4
4     1

One Hot Encodding

In [8]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
data=ohe.fit_transform(df2)
print(data)

[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]

In [9]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
data=ohe.fit_transform(df2[['city']])
data
# names=ohe.get_feature_names_out(['city'])
# names

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (5, 5)>

In [10]:
df=pd.DataFrame(data, columns=names)
df

NameError: name 'names' is not defined

In [ ]:
newdf=pd.DataFrame({'country':['india','america','pakistan ','uae',]})
data2=ohe.fit_transform(newdf[['country']])
names=ohe.get_feature_names_out(['country'])
names

array(['country_america', 'country_india', 'country_pakistan ',
       'country_uae'], dtype=object)

In [ ]:
dff=pd.DataFrame(data2, columns=names, dtype='int')
dff

   country_america  country_india  country_pakistan   country_uae
0                0              1                  0            0
1                1              0                  0            0
2                0              0                  1            0
3                0              0                  0            1

In [ ]:
newdf=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv', encoding='ISO-8859-1')
newdf

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [ ]:
ohe=OneHotEncoder()
data=ohe.fit_transform(newdf[['department']])
data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14999 stored elements and shape (14999, 10)>

In [ ]:
names=ohe.get_feature_names_out(['department'])
names

array(['department_IT', 'department_RandD', 'department_accounting',
       'department_hr', 'department_management', 'department_marketing',
       'department_product_mng', 'department_sales', 'department_support',
       'department_technical'], dtype=object)

In [ ]:
#  another way of doing one hot encodding 

# dfff=pd.get_dummies(newdf,dtype=int)
dfff=pd.get_dummies(newdf,dtype=int, drop_first=True)
dfff

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department_RandD,department_accounting,department_hr,department_management,department_marketing,department_product_mng,department_sales,department_support,department_technical,salary_low,salary_medium
0,1003,2,157,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0
1,1005,5,262,6,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,1486,7,272,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1
3,1038,5,223,5,0,1,0,0,0,0,0,0,0,1,0,0,1,0
4,1057,2,159,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14995,87673,2,160,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14996,87679,2,143,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14997,87681,6,280,4,0,1,0,0,0,0,0,0,0,0,1,0,1,0
14998,87684,2,158,3,0,1,0,0,0,0,0,0,0,0,1,0,1,0