In [9]:
import pandas as pd
from sklearn.datasets import load_breast_cancer, fetch_california_housing
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,f1_score,recall_score,precision_score, r2_score, mean_absolute_error

In [10]:
cdata=load_breast_cancer()

In [11]:
df=pd.DataFrame(cdata.data,columns=cdata.feature_names)
df['cancer']=cdata.target 
df

     mean radius  mean texture  ...  worst fractal dimension  cancer
0          17.99         10.38  ...                  0.11890       0
1          20.57         17.77  ...                  0.08902       0
2          19.69         21.25  ...                  0.08758       0
3          11.42         20.38  ...                  0.17300       0
4          20.29         14.34  ...                  0.07678       0
..           ...           ...  ...                      ...     ...
564        21.56         22.39  ...                  0.07115       0
565        20.13         28.25  ...                  0.06637       0
566        16.60         28.08  ...                  0.07820       0
567        20.60         29.33  ...                  0.12400       0
568         7.76         24.54  ...                  0.07039       1

[569 rows x 31 columns]

In [12]:
x=df.drop('cancer',axis=1)
y=df['cancer']

In [13]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [15]:
knn_model=KNeighborsClassifier(n_neighbors=10)
knn_model.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=10)

In [16]:
ypred=knn_model.predict(xtest)
ypred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [17]:
print('training score:', knn_model.score(xtrain,ytrain))
print('testing score:', knn_model.score(xtest,ytest))

training score: 0.9271356783919598
testing score: 0.9824561403508771

In [18]:
print("Accuracy:", accuracy_score(ytest, ypred))
print("Precision:", precision_score(ytest, ypred))
print("Recall:", recall_score(ytest, ypred))
print("F1 Score:", f1_score(ytest, ypred))

Accuracy: 0.9824561403508771
Precision: 0.981651376146789
Recall: 0.9907407407407407
F1 Score: 0.9861751152073732

In [19]:
print('mean_absolute_error:', mean_absolute_error(ytest, ypred))
print('confusion_matrix:\n', confusion_matrix(ytest, ypred))

mean_absolute_error: 0.017543859649122806
confusion_matrix:
 [[ 61   2]
 [  1 107]]

In [20]:
rdata=fetch_california_housing()
rdf=pd.DataFrame(rdata.data,columns=rdata.feature_names)
rdf['MedHouseVal']=rdata.target
rdf

       MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
0      8.3252      41.0  6.984127  ...     37.88    -122.23        4.526
1      8.3014      21.0  6.238137  ...     37.86    -122.22        3.585
2      7.2574      52.0  8.288136  ...     37.85    -122.24        3.521
3      5.6431      52.0  5.817352  ...     37.85    -122.25        3.413
4      3.8462      52.0  6.281853  ...     37.85    -122.25        3.422
...       ...       ...       ...  ...       ...        ...          ...
20635  1.5603      25.0  5.045455  ...     39.48    -121.09        0.781
20636  2.5568      18.0  6.114035  ...     39.49    -121.21        0.771
20637  1.7000      17.0  5.205543  ...     39.43    -121.22        0.923
20638  1.8672      18.0  5.329513  ...     39.43    -121.32        0.847
20639  2.3886      16.0  5.254717  ...     39.37    -121.24        0.894

[20640 rows x 9 columns]

In [21]:
x=rdf.drop('MedHouseVal',axis=1)
y=rdf['MedHouseVal']

In [22]:
knn_reg=KNeighborsRegressor(n_neighbors=5)
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)
knn_reg.fit(xtrain,ytrain)

KNeighborsRegressor()

In [23]:
ypred=knn_reg.predict(xtest)
ypred

array([1.623 , 1.0822, 2.8924, ..., 2.1312, 1.9486, 1.731 ], shape=(6192,))

In [25]:
print('training score:', knn_reg.score(xtrain,ytrain))
print('testing score:', knn_reg.score(xtest,ytest))

training score: 0.44109296411937404
testing score: 0.1337849088797427

In [26]:
print('r2_score:', r2_score(ytest, ypred))
print('mean_absolute_error:', mean_absolute_error(ytest, ypred))

r2_score: 0.1337849088797427
mean_absolute_error: 0.8217871040051679