In [2]:
import pandas as pd

In [4]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [6]:
df=pd.DataFrame({'Weight':[12,45,54,67,74,89],
'height':[145,146,167,170,145,187]})
df

   Weight  height
0      12     145
1      45     146
2      54     167
3      67     170
4      74     145
5      89     187

In [14]:
ss= scaler.fit_transform(df)
ss

array([[-1.83264789, -0.94118371],
       [-0.48371004, -0.87843813],
       [-0.1158179 ,  0.43921906],
       [ 0.41558186,  0.62745581],
       [ 0.7017202 , -0.94118371],
       [ 1.31487376,  1.69413067]])

In [13]:
dff=pd.DataFrame(ss, columns=df.columns)
dff

     Weight    height
0 -1.832648 -0.941184
1 -0.483710 -0.878438
2 -0.115818  0.439219
3  0.415582  0.627456
4  0.701720 -0.941184
5  1.314874  1.694131