SVM(support vector machine)

svm classifier

In [12]:
import pandas as pd 
from sklearn.svm import SVC, SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score, r2_score, mean_absolute_error, mean_squared_error

In [3]:
data =pd.read_csv('data/bankloan.csv')
data.head()

,ID,Age,Experience,Income,ZIP.Code,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [5]:
data.drop(['ZIP.Code','ID'], axis=1, inplace=True)
data

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0
4996,30,4,15,4,0.4,1,85,0,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,0,1,1

In [9]:
x=data.drop('Personal.Loan', axis=1)
y=data['Personal.Loan']

In [10]:
xtrain, xtest, ytrain, ytest =train_test_split(x, y, test_size=0.3, random_state=42)

In [18]:
clsSvcModel =SVC(kernel='rbf')
clsSvcModel.fit(xtrain, ytrain)

SVC()

In [19]:
ypred=clsSvcModel.predict(xtest)
ypred

array([0, 0, 0, ..., 0, 0, 0], shape=(1500,))

In [20]:
print('training score :', clsSvcModel.score(xtrain, ytrain))
print('testing score :', clsSvcModel.score(xtest, ytest))

training score : 0.914
testing score : 0.8993333333333333

In [ ]:
# print('recall_score :', recall_score(ytest, ypred))
# print('precision_score :', precision_score(ytest, ypred))
# print('f1_score :', f1_score(ytest, ypred))
# print('accuracy_score :', accuracy_score(ytest, ypred))

SVM Regressor

In [2]:
dfr= pd.read_csv('data/Student_Performance.csv')
dfr

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
dfr['Extracurricular Activities']= le.fit_transform(dfr['Extracurricular Activities'])
dfr.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0

In [4]:
x=dfr.drop('Performance Index', axis=1)
y=dfr['Performance Index']

In [5]:
xtrain, xtest, ytrain, ytest =train_test_split(x, y, test_size=0.3, random_state=42)

In [6]:
regSvcModel =SVR(kernel='linear', C=10, epsilon=0.01)
regSvcModel.fit(xtrain, ytrain)

SVR(C=10, epsilon=0.01, kernel='linear')

In [7]:
ypred=regSvcModel.predict(xtest)
ypred

array([54.72286355, 22.59381655, 47.9734295 , ..., 33.45429049,
       67.90975334, 31.24838632], shape=(3000,))

In [9]:
print('training score :', regSvcModel.score(xtrain, ytrain))
print('testing score :', regSvcModel.score(xtest, ytest))

training score : 0.9886162792018566
testing score : 0.9890003725745495

In [13]:
print('r2 score :', regSvcModel.score(xtest, ytest))
print('mean absolute error :', mean_absolute_error(ytest, ypred))
print('mean squared error :', mean_squared_error(ytest, ypred))

r2 score : 0.9890003725745495
mean absolute error : 1.610014881138679
mean squared error : 4.070519069610116