Car price prediction

In [36]:
import pandas as pd

In [37]:
data=pd.read_csv('car_price_prediction_with_missing.csv')
data

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1.0,Tesla,2016.0,2.3,Petrol,Manual,114832.0,New,26613.92,Model X
1,2.0,BMW,2018.0,4.4,Electric,Manual,143190.0,Used,14679.61,5 Series
2,3.0,Audi,2013.0,4.5,Electric,Manual,181601.0,New,44402.61,A4
3,4.0,Tesla,2011.0,4.1,Diesel,Automatic,68682.0,New,86374.33,Model Y
4,5.0,Ford,2009.0,2.6,Diesel,Manual,223009.0,Like New,73577.10,Mustang
...,...,...,...,...,...,...,...,...,...,...
2495,2496.0,Audi,2020.0,2.4,Petrol,Automatic,22650.0,Like New,61384.10,Q5
2496,2497.0,Audi,2001.0,5.7,Hybrid,Manual,77701.0,Like New,24710.35,A3
2497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2498,2499.0,Audi,2002.0,4.5,Diesel,Manual,229164.0,Like New,46085.67,Q5
2499,2500.0,Toyota,2005.0,4.6,Diesel,Automatic,80978.0,Used,16594.14,RAV4

In [38]:
data.isna().sum()

Car ID          250
Brand           250
Year            250
Engine Size     250
Fuel Type       250
Transmission    250
Mileage         250
Condition       250
Price           250
Model           250
dtype: int64

In [39]:
data=data.dropna()
data.isna().sum()

Car ID          0
Brand           0
Year            0
Engine Size     0
Fuel Type       0
Transmission    0
Mileage         0
Condition       0
Price           0
Model           0
dtype: int64

In [40]:
data

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1.0,Tesla,2016.0,2.3,Petrol,Manual,114832.0,New,26613.92,Model X
1,2.0,BMW,2018.0,4.4,Electric,Manual,143190.0,Used,14679.61,5 Series
2,3.0,Audi,2013.0,4.5,Electric,Manual,181601.0,New,44402.61,A4
3,4.0,Tesla,2011.0,4.1,Diesel,Automatic,68682.0,New,86374.33,Model Y
4,5.0,Ford,2009.0,2.6,Diesel,Manual,223009.0,Like New,73577.10,Mustang
...,...,...,...,...,...,...,...,...,...,...
2494,2495.0,Mercedes,2001.0,2.3,Petrol,Manual,162586.0,Used,90378.98,E-Class
2495,2496.0,Audi,2020.0,2.4,Petrol,Automatic,22650.0,Like New,61384.10,Q5
2496,2497.0,Audi,2001.0,5.7,Hybrid,Manual,77701.0,Like New,24710.35,A3
2498,2499.0,Audi,2002.0,4.5,Diesel,Manual,229164.0,Like New,46085.67,Q5
2499,2500.0,Toyota,2005.0,4.6,Diesel,Automatic,80978.0,Used,16594.14,RAV4

In [41]:
df=pd.get_dummies(data,drop_first=True, dtype=int)
df

,Car ID,Year,Engine Size,Mileage,Price,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Mercedes,Brand_Tesla,...,Model_Model S,Model_Model X,Model_Model Y,Model_Mustang,Model_Prius,Model_Q5,Model_Q7,Model_RAV4,Model_X3,Model_X5
0,1.0,2016.0,2.3,114832.0,26613.92,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
1,2.0,2018.0,4.4,143190.0,14679.61,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2013.0,4.5,181601.0,44402.61,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4.0,2011.0,4.1,68682.0,86374.33,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
4,5.0,2009.0,2.6,223009.0,73577.10,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2495.0,2001.0,2.3,162586.0,90378.98,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2495,2496.0,2020.0,2.4,22650.0,61384.10,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2496,2497.0,2001.0,5.7,77701.0,24710.35,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2498,2499.0,2002.0,4.5,229164.0,46085.67,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2499,2500.0,2005.0,4.6,80978.0,16594.14,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [49]:
# x=df.drop('Price',axis=1)
# y=df.Price
# x
x=df[['Year', 'Engine Size', 'Mileage']]
y=df['Price']

In [43]:
# from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,f1_score,recall_score,precision_score

In [50]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y, test_size=0.3, random_state=42)

In [51]:
# knrmodel=KNeighborsRegressor(n_neighbors=5)
# knrmodel.fit(xtrain,ytrain)
model=LinearRegression()
# model=Lasso()
model.fit(xtrain,ytrain)

LinearRegression()

In [52]:
ypred=model.predict(xtest)
ypred

array([53796.69378737, 51046.10968719, 53848.80709701, 54689.12588568,
       52317.70021566, 55011.97426235, 50342.78949371, 49873.46687606,
       50584.47686803, 51711.99578407, 52295.49761973, 53982.72522374,
       53209.07949936, 50386.67341193, 53329.71758483, 51430.40486643,
       52849.42424114, 50389.68727278, 51634.45040149, 54726.70230314,
       53187.53512631, 51285.72571061, 52553.80666608, 52702.23851479,
       51821.96707173, 52733.64344434, 49680.30196044, 55121.51595779,
       49560.92205951, 51429.39956057, 52116.08257488, 49560.86279264,
       54977.96536584, 53973.05898643, 50779.7632264 , 50978.89981828,
       54237.70163052, 52567.43259823, 49563.7457952 , 50276.65469692,
       52028.35601096, 53798.93579959, 49940.60906511, 50660.60481664,
       50210.02947839, 50627.92094129, 54904.16000537, 52347.06432085,
       51044.19957604, 52056.86638463, 51693.30509789, 52327.7934406 ,
       50718.05210014, 53792.79669276, 54922.83311005, 50475.47421408,
       53839.93004873, 53416.81430517, 54027.28946906, 53088.53344438,
       54436.19482597, 51592.68368952, 53639.61788133, 49992.70230878,
       54339.46964506, 53039.8106383 , 54213.06285659, 52107.72559578,
       49510.31533254, 53358.2944488 , 50390.2878394 , 52237.68947788,
       54547.76886069, 54197.97612524, 51119.72587107, 51687.04158872,
       50048.73740066, 54364.08637468, 50919.81257986, 53060.75281545,
       49471.18598006, 52667.99969282, 54990.61874349, 53222.40777531,
       53775.32700718, 51700.36270125, 53122.88361558, 50443.66659016,
       52843.27801622, 50579.92067133, 50168.6743495 , 54524.19881488,
       49904.66458387, 53166.82279603, 51782.18375417, 52004.80896065,
       54617.85768231, 51589.91314445, 51454.41648258, 50523.81160344,
       50985.68793689, 51127.47625525, 50854.81998109, 50944.34771575,
       50809.80046213, 52415.19571854, 53760.55143672, 53122.54868226,
       54599.9690637 , 53098.4261141 , 54767.50478042, 53008.33250945,
       51880.51933048, 54648.23641243, 50761.19977884, 52643.0695921 ,
       54525.29543715, 50622.10425394, 54844.80803689, 51126.73828122,
       54051.15330494, 54227.73084155, 52858.92643833, 51048.46698404,
       52611.54563193, 52890.82426212, 52214.80113801, 49981.96482949,
       50431.59911521, 52831.54803103, 53228.73562185, 50591.35892885,
       51360.8837667 , 52888.5542651 , 53723.38612663, 52075.72172513,
       52229.91254503, 50709.50663711, 52784.16902914, 54119.43009822,
       50303.18063436, 50104.5950262 , 51384.69454772, 50085.39998574,
       51436.77831263, 51293.56149475, 52916.31117889, 50039.58330709,
       50029.23870905, 51450.86303529, 49752.37116835, 53310.32733675,
       51846.12374627, 51510.71109553, 54863.95551141, 51438.67113407,
       50866.40037941, 53492.00587473, 50979.9887323 , 51928.49218452,
       54663.55464679, 53606.1485232 , 53851.60621715, 54552.46888099,
       54038.89954431, 51234.28180386, 52195.17126307, 53799.22289911,
       54632.34983285, 50510.0630516 , 52777.27709781, 51444.27961513,
       51907.10325195, 53922.42824604, 51985.90595171, 54015.98465304,
       52708.09965463, 52712.64503235, 51543.37764527, 51242.74554652,
       50423.24776079, 50074.5517862 , 53037.58526824, 51164.63391436,
       52558.75996857, 55034.89105066, 55243.25475149, 51065.40291833,
       52324.3226955 , 52381.35789893, 52147.38123502, 53420.13425924,
       50003.89954854, 53548.23479811, 49692.07208314, 55076.82912868,
       53620.48910863, 51969.40578839, 53921.22240627, 50693.66144735,
       50091.17852599, 52868.62560168, 54734.82663498, 54645.08473508,
       54909.76620698, 50296.13878199, 50549.72580894, 49963.52844595,
       49649.25965073, 51988.39781036, 52546.74736146, 52469.29061882,
       53670.43323771, 51148.01683715, 51341.8003258 , 55154.62245783,
       53937.82164882, 53870.11207781, 51511.12410276, 53491.1280938 ,
       52112.97550058, 54420.92631048, 50049.66211203, 52364.89327821,
       49706.81742534, 51593.62028575, 54273.84159921, 49592.41802292,
       50721.79192364, 52671.55852096, 54690.93081996, 52857.48050797,
       54394.31293746, 54551.11539943, 53667.04415559, 50083.75710118,
       54201.49876332, 51924.76593505, 54685.82664786, 53347.46901301,
       50961.33172485, 53537.62689407, 51008.51474239, 50420.45919733,
       49869.5927438 , 51633.56304853, 54832.46304378, 50246.90615946,
       51302.1415731 , 52448.63928069, 51063.46726163, 53305.67568313,
       55064.58537696, 50477.86437695, 54892.08946229, 51707.26879679,
       50429.95661307, 50531.45408905, 51666.27924779, 53427.57400345,
       51601.51038355, 55264.13292848, 52104.30892325, 54153.48777699,
       49950.33123603, 51452.89602203, 54416.20024123, 52036.63159484,
       55349.7233405 , 54641.07445149, 54580.04210163, 52692.84170778,
       50267.49563819, 51389.99074485, 54481.84727795, 51919.27535233,
       53454.66117998, 52798.33092531, 51089.90731427, 52524.91968296,
       49684.96594125, 54227.73214842, 54034.13379847, 53686.53468726,
       49937.16860829, 54205.97280006, 50169.45677874, 53584.85353011,
       51455.36957042, 53328.15936224, 54158.73355975, 52444.26339592,
       50348.56737445, 54217.75595457, 51648.64085793, 52113.88023653,
       53859.18318769, 54168.58795584, 52939.43234059, 53144.68092449,
       53327.71585887, 54361.43645898, 54129.08451993, 53699.49913262,
       52910.80600159, 52767.26409049, 54362.61496141, 50655.85460198,
       54716.38474133, 54567.28018983, 55064.71386525, 53591.19613386,
       54701.84139981, 52200.83945071, 54477.62123584, 52336.09911425,
       55134.04398462, 54446.853885  , 54396.51605263, 53099.47749522,
       51062.00139456, 51590.26422303, 54774.30505173, 53807.31636446,
       50751.26673984, 52978.64298306, 52632.72454239, 49862.25717062,
       50916.09929306, 53847.59456942, 52400.0099984 , 54318.99397873,
       50962.26576452, 55436.80283773, 55128.4251907 , 51391.75892294,
       54731.67901956, 52107.45563543, 50271.97681704, 53179.43454276,
       51702.19980888, 53066.00907369, 54851.33648397, 53065.45566939,
       54295.26717067, 53164.6389036 , 49757.48110372, 50370.67334509,
       51484.54263524, 53681.1738997 , 55189.72009378, 52287.21680557,
       52728.38924575, 50312.8335507 , 50515.80236967, 53569.93934515,
       51042.84426669, 54634.57087586, 52358.01214456, 50746.94646647,
       54376.7928737 , 50098.12696914, 54119.31166688, 50129.19065725,
       52780.38901085, 50189.97064945, 53113.52166489, 54270.29486366,
       53125.01558826, 51625.81705131, 50229.02470426, 52161.48742662,
       50907.80493802, 52611.98924053, 50596.11026393, 50008.46718115,
       54361.97539524, 52723.25506246, 50474.54297478, 53449.97812709,
       50558.98726819, 54929.16162807, 53204.50278239, 55231.57070022,
       52789.31527177, 53746.26383133, 54060.17153906, 50205.26917341,
       52525.72092859, 54592.36659829, 53629.22684963, 52369.62919941,
       51227.06571298, 51090.86058865, 49342.46470609, 52218.56824168,
       50077.04934802, 50173.8921142 , 52732.07277735, 49944.73986088,
       54642.72357209, 51151.27649448, 50077.22194236, 50703.09486283,
       53388.22446656, 52553.86371087, 51181.19858691, 53415.94715941,
       54437.38734488, 53366.04662761, 50058.85285645, 50194.23940954,
       50977.56879011, 51504.03118857, 51209.66109353, 51495.52627863,
       50979.6059441 , 52933.19045092, 53918.65235902, 50838.22242773,
       52053.9438468 , 50810.35442061, 54035.98970119, 54062.52680951,
       52658.656432  , 52085.52958516, 49959.41636407, 54585.80032002,
       53363.51206294, 49433.25556917, 53209.96824982, 50574.52890282,
       51333.78883376, 53435.62493739, 52352.29180824, 52644.14953622,
       50418.28257355, 52813.5199999 , 50471.74724791, 54278.14266191,
       54589.5460453 , 53310.77497138, 50771.10455321, 53017.20524265,
       52414.86555472, 54527.27113536, 55090.58491317, 50127.86831916,
       53935.44599932, 55236.31991847, 50233.25036678, 54202.4145048 ,
       54313.92247687, 53076.46343144, 52244.67863663, 54579.62764894,
       53037.53602234, 53219.718812  , 53985.18040742, 52216.41243665,
       54186.74979882, 52751.68495622, 51666.30345972, 51746.53374369,
       49740.41900854, 49639.71186594, 49859.08475309, 51792.18465694,
       50267.56317033, 50864.60111787, 52692.01198969, 50165.10048717,
       53215.44377706, 53815.02493402, 52571.88882432, 52457.05109437,
       52269.42483627, 54556.42165341, 49729.19621389, 52819.11485888,
       53883.60215964, 52125.58183047, 49766.08879651, 52600.81109424,
       50865.76532683, 51145.50691216, 54214.9051133 , 52430.81194338,
       49732.04679937, 50849.75148735, 52813.11568548, 54837.3965426 ,
       53149.15741516, 50059.00477996, 51384.21294532, 53691.40068071,
       50706.17363926, 55038.89617047, 54859.84766604, 52530.5976745 ,
       54879.6664644 , 53900.97706252, 51636.25236091, 54934.57428732,
       53895.95696871, 53549.33261006, 51612.08420241, 49672.82627012,
       52299.42409938, 54196.1974958 , 55202.77513613, 51753.20174178,
       50774.82289865, 52375.1758303 , 50904.7701625 , 50708.47534872,
       52708.11127435, 52880.78249329, 50600.80510839, 49267.82811283,
       51735.5614189 , 55375.20411166, 52161.28772943, 55122.44820294,
       51571.20029666, 50647.04911176, 54217.91295782, 53862.96982444,
       52127.48208317, 54459.26287837, 52288.91369995, 53805.34000684,
       54350.85290547, 51369.598973  , 53326.9160587 , 50086.74997152,
       52664.14784861, 54964.34762688, 50541.42388423, 51477.80871573,
       54863.73351129, 52606.34855012, 49957.73894549, 53270.87301747,
       54606.21953172, 54287.41986008, 52718.77479892, 53227.55701409,
       54314.39473901, 54606.99588472, 54350.40932363, 53550.97547059,
       52317.9656385 , 50878.68902323, 51464.92825823, 54619.7141752 ,
       53425.49974694, 52429.09481767, 49921.81467154, 52048.88030899,
       50355.73231957, 50162.24788736, 54813.86895887, 54247.31971173,
       52707.98939529, 52681.18777022, 54808.42732103, 53677.91453153,
       50948.64808295, 54155.61054791, 53502.46476087, 52404.9363698 ,
       52945.32586152, 54701.55151199, 53138.15701503, 54840.73319886,
       54643.7330813 , 54290.75062381, 55073.79839105, 51414.90656397,
       51794.46733954, 52007.5193929 , 53927.33249842, 55284.14271003,
       52877.70753495, 50113.54661014, 51839.18439966, 52798.31888718,
       52992.1714466 , 50510.89080059, 53012.71474756, 49474.69644435,
       54233.70458933, 53692.01165995, 50667.7162461 , 50629.73769107,
       51828.4880183 , 54563.16082724, 54161.71807439, 51321.97531249,
       53875.4514897 , 50993.25345033, 51655.12788467, 51350.51642612,
       52150.49248865, 54335.90809785, 52032.38768217, 53447.03612258,
       51438.18792368, 52315.19923655, 52044.29377878, 54943.60837756,
       51345.40942961, 51582.31276262, 53658.43607125, 50602.02671122,
       50650.89118524, 50605.70584642, 53941.102001  , 55024.2708102 ,
       50628.84191306, 50541.17877119, 53348.96572527, 54641.50484162,
       55185.09417886, 51082.05356904, 54131.26344436, 50397.99880288,
       51904.33440812, 53580.89684622, 49872.86978402, 54406.35206921,
       50020.56965649, 52006.13066052, 54503.17496531, 54005.79800954,
       53473.23324838, 54231.91556856, 50965.05299719, 52915.50395951,
       52985.39566441, 51048.78801534, 52865.47896808, 49861.19838226,
       53509.8332241 , 51207.85435549, 51336.34801671, 52284.19582389,
       52492.43903657, 53127.07901374, 52038.36495909, 49952.74874831,
       51261.249923  , 52217.64381935, 52674.72480495, 50148.10799291,
       50717.53441292, 53713.7415448 , 54647.65540565, 49746.24908611,
       54446.31839648, 52545.7667617 , 54761.58951346, 53324.03019848,
       54004.95359426, 51807.81374184, 50645.39106648, 49826.65325933,
       54138.2960978 , 52487.33460867, 49882.178267  , 50029.94882755,
       50613.36930124, 51433.90446368, 54667.57483404])

In [53]:
print('training score:', model.score(xtrain,ytrain))
print('testing score:', model.score(xtest,ytest))

training score: 0.003550611839877482
testing score: -0.005944189184359239